ARCH_WITH_SUB_TO_ARCH_MAP: dict[str, str] = {
    "aarch64": "AArch64",
    "aarch64_32": "AArch64",
    "aarch64_be": "AArch64",
    "amdgcn": "AMDGPU",
    "arc": "ARC",
    "arm": "ARM",
    # "arm64": "AArch64",
    # "arm64_32": "AArch64",
    "armeb": "ARM",
    "avr": "AVR",
    "bpf": "BPF",
    "bpfeb": "BPF",
    "bpfel": "BPF",
    "csky": "CSKY",
    "hexagon": "Hexagon",
    "lanai": "Lanai",
    "loongarch32": "LoongArch",
    "loongarch64": "LoongArch",
    "m68k": "M68k",
    "mips": "Mips",
    "mips64": "Mips",
    "mips64el": "Mips",
    "mipsel": "Mips",
    "msp430": "MSP430",
    "nvptx": "NVPTX",
    "nvptx64": "NVPTX",
    "ppc32": "PPC",
    "ppc32le": "PPC",
    "ppc64": "PPC",
    "ppc64le": "PPC",
    "r600": "R600",
    "riscv32": "RISCV",
    "riscv64": "RISCV",
    "sparc": "Sparc",
    "sparcel": "Sparc",
    "sparcv9": "Sparc",
    "systemz": "SystemZ",
    "thumb": "ARM",
    "thumbeb": "ARM",
    "ve": "VE",
    "wasm32": "WebAssembly",
    "wasm64": "WebAssembly",
    "i686": "X86",
    "x86_64": "X86",
    "xcore": "XCore",
}
